import Head from "next/head";
import Header from "./Header/Header";
import { Inter, Plus_Jakarta_Sans } from "next/font/google";
const pjs = Plus_Jakarta_Sans({ subsets: ["latin"] });

export default function Layout({ children }) {
  return (
    <>
      <Head>
        <title>Nancy Hodnefield | Professional Coach</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className={`${pjs.className}`}>{children}</main>
    </>
  );
}
